### ISSUE TITLE
Photo map view

### ISSUE THREAD

**Issue by gitizenme** [gitizenme/Fotomat#2]
## User Story
As a user I would like to view a map with the locations of the photos I have taken.

## Tasks

- [ ] Create Github repository and clone to my local development environment
- [ ] Create an Android Studio project in my local repository, use the map activity template
- [ ] Configure the map view to work with Google Maps API
- [ ] UI Test
